name: github pages
on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: patrickweaver/actions-eleventy@master
        with:
          install_dependencies: true
      - name: CNAME
        run: echo 'www.phoneboothpress.com' | sudo tee _site/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
